using WinnersPortal.Services.Activity;
using WinnersPortal.Services.Ai;
using WinnersPortal.Services.Opportunities;
using WinnersPortal.Services.GitHub;
using WinnersPortal.Services.Phone;

namespace WinnersPortal.Services.Settings;

/// <summary>A configurable value the portal knows about. Unknown keys are rejected everywhere.</summary>
/// <param name="HelpRequired">
/// True when this field costs money, breaks an integration, cannot be undone, or uses
/// domain jargon — see HelpRegistry's coverage rule. A required topic that is missing
/// fails the build, so this is what keeps documentation in step with the settings.
/// </param>
/// <param name="Choices">
/// The values this setting accepts, when it is a choice rather than free
/// text — the screen renders a dropdown and the service refuses anything
/// else, so a typo cannot quietly switch a feature off.
/// </param>
/// <param name="IsMultiline">
/// True when the value is a document rather than a line — the screen gives it a
/// text area. Never combined with IsSecret or IsBoolean, which render as a masked
/// one-line box and a switch; the registry tests hold that line.
/// </param>
/// <param name="MainOnlyDefault">
/// True when the default describes the bundled local stack — Mailpit on
/// localhost, MinIO on port 9000 — rather than a convention. The main setup
/// keeps it, as it always had; a setup added beside it starts blank, since
/// a second SMTP server that already answers to "localhost" would look
/// configured and be nothing of the kind.
/// </param>
/// <param name="Trimmed">
/// True when a space around the value can only be a paste's leftover — a
/// key, a bucket, an address. It is saved without it: an access key with a
/// trailing space is a different key, and the store says only that it has
/// never heard of it.
/// </param>
public sealed record SettingDefinition(
    string Key,
    string Group,
    string Label,
    bool IsSecret = false,
    string? Default = null,
    bool HelpRequired = false,
    bool IsBoolean = false,
    bool IsMultiline = false,
    IReadOnlyList<SettingChoice>? Choices = null,
    bool MainOnlyDefault = false,
    bool Trimmed = false);

/// <summary>One option of a choice setting: what is stored, and what the screen shows.</summary>
public sealed record SettingChoice(string Value, string Label);

/// <summary>
/// The catalogue of every setting, grouped the way the blueprint's
/// Configuration section groups them. Resolution order for a value: stored
/// row → environment variable → default. What is saved on the screen wins;
/// a deployment's variable is the value in force only while nothing is
/// saved, and never locks a field.
/// Env convention: <c>branding.portalName</c> → <c>WP_BRANDING_PORTALNAME</c>.
/// </summary>
public static class SettingsRegistry
{
    public const string SystemGroup = "system";

    public static readonly IReadOnlyList<(string Name, string Label)> Groups =
    [
        ("branding", "Branding"),
        ("github", "GitHub"),
        ("storage", "Storage"),
        ("email", "Email"),
        ("phone", "Phone messages"),
        ("identity", "Identity verification"),
        ("preview", "Build host"),
        ("opportunity", "Opportunity policy"),
        ("ai", "AI automation"),
        (Ai.EvalSettings.Group, "AI evals"),
        ("legal", "Legal"),
        ("notifications", "Notifications"),
        ("limits", "Limits & maintenance"),
        (RedisSettings.Group, "Redis (a second API process)"),
        (Auth.JwtSettings.Group, "JWT (token signing & lifetimes)"),
        ("integrations", "Integrations & feature flags"),
    ];

    public static readonly IReadOnlyList<SettingDefinition> All =
    [
        // system — internal flags, never shown or editable in the admin screen
        new("system.setupCompleted", SystemGroup, "Setup completed", Default: "false"),
        new("system.digestLastDate", SystemGroup, "Last digest date"),
        new("system.aiNarrativeLastDate", SystemGroup, "Last narrative date"),
        // The web push identity, generated by the portal the first time it is
        // needed and never typed: a pair an operator could edit is a pair an
        // operator could break, and a changed pair orphans every subscription.
        new("system.pushPublicKey", SystemGroup, "Web push public key"),
        new("system.pushPrivateKey", SystemGroup, "Web push private key", IsSecret: true),
        // The uploaded brand images as data URLs, each with the stamp its
        // public URL carries (Settings/Logo.cs). Written by the upload
        // endpoints, never typed.
        new(BrandImage.Logo.DataKey, SystemGroup, "Uploaded logo"),
        new(BrandImage.Logo.StampKey, SystemGroup, "Uploaded logo stamp"),
        new(BrandImage.Icon.DataKey, SystemGroup, "Uploaded tab icon"),
        new(BrandImage.Icon.StampKey, SystemGroup, "Uploaded tab icon stamp"),

        // branding — self-evident, deliberately no help… except the two
        // addresses: the Web URL silently breaks every emailed link when it
        // is wrong, and the API URL, set, is where every page sends the
        // browser for the API (WebOrigin) — blank is the pages' own origin.
        new("branding.portalName", "branding", "Portal name", Default: "Winners Portal"),
        new(WebOrigin.WebUrlKey, "branding", "Web URL", Default: "http://localhost", HelpRequired: true),
        new(WebOrigin.ApiUrlKey, "branding", "API URL", HelpRequired: true),
        new("branding.accentColor", "branding", "Accent color", Default: "#0f766e"),
        new("branding.logoUrl", "branding", "Logo URL"),

        // The list of setups each connection keeps, in order (Settings/Setups.cs).
        // Written by the settings screen as one JSON value; never rendered as a field.
        new(Setups.GitHub.ListKey, "github", "GitHub setups", HelpRequired: true),
        new(Setups.Storage.ListKey, "storage", "Storage setups", HelpRequired: true),
        new(Setups.Email.ListKey, "email", "Email setups", HelpRequired: true),
        new(Setups.Phone.ListKey, "phone", "Phone message setups", HelpRequired: true),
        new(Setups.Ai.ListKey, "ai", "AI provider setups", HelpRequired: true),
        new(Setups.Identity.ListKey, "identity", "Identity verification setups", HelpRequired: true),
        new(Setups.Preview.ListKey, "preview", "Build host setups", HelpRequired: true),

        // github — one setup's fields (Setups.GitHub)
        new("github.appId", "github", "GitHub App ID", HelpRequired: true),
        new("github.appSlug", "github", "GitHub App slug", HelpRequired: true),
        new("github.organization", "github", "Opportunity organization", HelpRequired: true),
        new("github.privateKey", "github", "App private key (PEM)", IsSecret: true, HelpRequired: true),
        new("github.webhookSecret", "github", "Webhook secret", IsSecret: true, HelpRequired: true),
        new("github.clientId", "github", "App client ID", HelpRequired: true),
        new("github.clientSecret", "github", "App client secret", IsSecret: true, HelpRequired: true),
        new(GitHub.GitHubService.TransferTokenKey, "github", "Transfer token (an owner's classic token)", IsSecret: true, HelpRequired: true),

        // storage — one setup's fields (Setups.Storage)
        new("storage.endpoint", "storage", "S3 endpoint", Default: "http://localhost:9000", HelpRequired: true, MainOnlyDefault: true, Trimmed: true),
        new("storage.publicUrl", "storage", "Public base URL", HelpRequired: true, Trimmed: true),
        new("storage.bucket", "storage", "Bucket", Default: "winnersportal", HelpRequired: true, Trimmed: true),
        new("storage.region", "storage", "Signing region", Default: "us-east-1", HelpRequired: true, Trimmed: true),
        new("storage.accessKey", "storage", "Access key", HelpRequired: true, Trimmed: true),
        new("storage.secretKey", "storage", "Secret key", IsSecret: true, HelpRequired: true, Trimmed: true),

        // email — one setup's fields (Setups.Email): an SMTP server, or a
        // mail service's HTTPS API (Email/EmailProviders.cs). SMTP by
        // default, which is what every setup saved before the choice was.
        new(Email.EmailProviders.ProviderKey, "email", "Send through", Default: Email.EmailProviders.Smtp,
            HelpRequired: true,
            Choices: [.. Email.EmailProviders.Choices.Select(c => new SettingChoice(c.Value, c.Label))]),
        new("email.smtpHost", "email", "SMTP host", Default: "localhost", HelpRequired: true, MainOnlyDefault: true, Trimmed: true),
        new("email.smtpPort", "email", "SMTP port", Default: "1025", HelpRequired: true, MainOnlyDefault: true, Trimmed: true),
        new("email.fromAddress", "email", "From address", Default: "no-reply@winnersportal.local", HelpRequired: true, MainOnlyDefault: true, Trimmed: true),
        new("email.smtpUser", "email", "SMTP user", HelpRequired: true, Trimmed: true),
        new("email.smtpPassword", "email", "SMTP password", IsSecret: true, HelpRequired: true),
        new(Email.EmailProviders.ApiKeyKey, "email", "API key", IsSecret: true, HelpRequired: true, Trimmed: true),
        new(Email.EmailProviders.DomainKey, "email", "Mailgun sending domain", HelpRequired: true, Trimmed: true),
        new(Email.EmailProviders.RegionKey, "email", "Mailgun region", Default: Email.EmailProviders.RegionUs,
            HelpRequired: true,
            Choices: [.. Email.EmailProviders.Regions.Select(c => new SettingChoice(c.Value, c.Label))]),

        // phone messages — one setup's fields (Setups.Phone): an SMS gateway
        // confirmation codes go through.
        // The provider carries its own address and request shape, so the
        // three fields under it are inert unless the choice is "custom".
        // Off by default: registration then confirms by email alone, and
        // the join form's phone field says so rather than promising a text.
        new(Phone.PhoneSender.ProviderKey, "phone", "SMS provider", Default: Phone.PhoneProviders.None,
            HelpRequired: true,
            Choices: [.. Phone.PhoneProviders.Choices.Select(c => new SettingChoice(c.Value, c.Label))]),
        new(Phone.PhoneSender.ApiKeyKey, "phone", "API key", IsSecret: true, HelpRequired: true),
        new(Phone.PhoneSender.SenderKey, "phone", "Sender ID or from-number", HelpRequired: true),
        new(Phone.PhoneSender.UrlKey, "phone", "Custom: request URL", HelpRequired: true),
        new(Phone.PhoneSender.HeaderKey, "phone", "Custom: API key header", Default: Phone.PhoneSender.DefaultHeader, HelpRequired: true),
        new(Phone.PhoneSender.BodyKey, "phone", "Custom: request body", Default: Phone.PhoneSender.DefaultBody, HelpRequired: true),

        // identity verification — identity.enabled is the master switch;
        // the provider and its credentials are one setup's fields
        // (Setups.Identity): Didit's key, workflow and webhook secret, or
        // Shufti Pro's client ID and secret key. The three "require"
        // switches say which doors ask for it. Off by default: a portal verifies nobody
        // until an operator has a provider account and has chosen to.
        new(Identity.IdentityKeys.Enabled, "identity", "Enable identity verification", Default: "false", HelpRequired: true, IsBoolean: true),
        new(Identity.IdentityKeys.Provider, "identity", "Verification provider", Default: Identity.IdentityProviders.Didit,
            HelpRequired: true,
            Choices: [.. Identity.IdentityProviders.Choices.Select(c => new SettingChoice(c.Value, c.Label))]),
        new(Identity.IdentityKeys.ClientId, "identity", "Client ID", HelpRequired: true, Trimmed: true),
        new(Identity.IdentityKeys.ApiKey, "identity", "API key", IsSecret: true, HelpRequired: true),
        new(Identity.IdentityKeys.WorkflowId, "identity", "Workflow ID", HelpRequired: true),
        new(Identity.IdentityKeys.WebhookSecret, "identity", "Webhook secret", IsSecret: true, HelpRequired: true),
        new(Identity.IdentityKeys.RequireForPublish, "identity", "Clients verify before publishing an opportunity", Default: "true", HelpRequired: true, IsBoolean: true),
        new(Identity.IdentityKeys.RequireForApply, "identity", "Freelancers verify before applying", Default: "true", HelpRequired: true, IsBoolean: true),
        new(Identity.IdentityKeys.RequireForPayments, "identity", "Payment details reach clients only from verified freelancers", Default: "true", HelpRequired: true, IsBoolean: true),

        // build host — one Linux server of its own, running the portal's
        // build agent, that builds each claimed milestone of an opportunity
        // requiring Docker Compose (Setups.Preview). Nothing runs until an
        // operator has stood one up and pasted its address and token here.
        new(Preview.PreviewHostKeys.HostUrl, "preview", "Host address", HelpRequired: true),
        new(Preview.PreviewHostKeys.Token, "preview", "Agent token", IsSecret: true, HelpRequired: true),
        new(Preview.PreviewHostKeys.BuildTimeoutMinutes, "preview", "Build timeout (minutes)",
            Default: $"{Preview.PreviewHost.DefaultTimeoutMinutes}", HelpRequired: true),
        // A built milestone run on the same host, behind an address of its
        // own under this parent; blank keeps the host to builds.
        new(Preview.PreviewHostKeys.RunUrl, "preview", "Preview address", HelpRequired: true),
        new(Preview.PreviewHostKeys.IdleMinutes, "preview", "Idle stop (minutes)",
            Default: $"{Preview.PreviewHost.DefaultIdleMinutes}", HelpRequired: true),
        new(Preview.PreviewHostKeys.MaxRunning, "preview", "Previews running at once",
            Default: $"{Preview.PreviewHost.DefaultMaxRunning}", HelpRequired: true),

        // opportunity policy
        new("opportunity.minAwardUsd", "opportunity", "Minimum award (USD)", Default: "100", HelpRequired: true),
        new("opportunity.defaultDurationDays", "opportunity", "Default opportunity duration (days)", Default: "14", HelpRequired: true),
        new("opportunity.reviewWindowDays", "opportunity", "Client review window (days)", Default: "7", HelpRequired: true),

        // ai automation — ai.enabled is the master switch; everything else is
        // inert while it is off. Off by default so no deployment starts
        // sending data anywhere without someone choosing to. Provider, key
        // and model are one setup's fields (Setups.Ai); the rest govern all.
        new("ai.enabled", "ai", "Enable AI automation", Default: "false", HelpRequired: true, IsBoolean: true),
        new("ai.provider", "ai", "Model provider", Default: AiProviders.Gemini, HelpRequired: true,
            Choices: [.. AiProviders.Choices.Select(c => new SettingChoice(c.Value, c.Label))]),
        new("ai.apiKey", "ai", "Provider API key", IsSecret: true, HelpRequired: true),
        new("ai.model", "ai", "Model", HelpRequired: true),
        new(AiOptions.StandbyKey, "ai", "Standby for the active setup", Default: "false", HelpRequired: true, IsBoolean: true),
        new("ai.dailyCallLimit", "ai", "Daily call limit", Default: "200", HelpRequired: true),
        // What bounds one call and one member (Ai/AiLimits.cs): read live
        // on every call, so a saved change is in force for the next one.
        new(AiLimits.CallTimeoutKey, "ai", "Call timeout (seconds)", Default: $"{AiLimits.DefaultCallTimeoutSeconds}", HelpRequired: true),
        new(AiLimits.RetriesKey, "ai", "Retries per call", Default: $"{AiLimits.DefaultRetries}", HelpRequired: true),
        new(AiLimits.PauseKey, "ai", "Pause after repeated failures (seconds)", Default: $"{AiLimits.DefaultPauseSeconds}", HelpRequired: true),
        new(AiLimits.MemberDailyKey, "ai", "Inline tool calls per member per day", Default: $"{AiLimits.DefaultMemberDaily}", HelpRequired: true),
        new(AiLimits.MemberPerMinuteKey, "ai", "Inline tool calls per member per minute", Default: $"{AiLimits.DefaultMemberPerMinute}", HelpRequired: true),
        // What a call costs and what a day may cost (Ai/AiPrices.cs): the
        // prices are the operator's to copy from the provider's page, and
        // the budget is measured against them, so with none saved it never trips.
        new(AiPrices.Key, "ai", "Model prices (USD per million tokens)", HelpRequired: true, IsMultiline: true),
        new(AiPrices.BudgetKey, "ai", "Daily spend budget (USD)", HelpRequired: true),
        // A different model for a feature (Ai/AiFeatureModels.cs): the quick
        // inline tools on a quick model, the long reads on the stronger one.
        new(AiFeatureModels.Key, "ai", "Model per feature", HelpRequired: true, IsMultiline: true),
        // How long a call's prompt and answer stay on its activity row
        // (Ai/AiRetention.cs). Swept whether or not the switch is on: rows
        // from before it was turned off are the ones most worth clearing.
        new(AiRetention.Key, "ai", "AI call bodies kept (days)", Default: $"{AiRetention.DefaultDays}", HelpRequired: true),
        new("ai.sendCodeToProvider", "ai", "Send code excerpts to provider", Default: "false", HelpRequired: true, IsBoolean: true),
        new("ai.features.entryDigest", "ai", "Entry review digests", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.milestoneExtraction", "ai", "Milestone extraction from briefs", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.briefCoach", "ai", "Opportunity brief coach", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.spamFilter", "ai", "Spam & duplicate entry filter", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.progressNarrative", "ai", "Daily progress narratives", Default: "false", HelpRequired: true, IsBoolean: true),
        new("ai.features.seoMetadata", "ai", "SEO metadata drafts", Default: "false", HelpRequired: true, IsBoolean: true),
        new("ai.features.standingNotes", "ai", "Standing notes on the progress board", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.categorySuggestion", "ai", "Category suggestions on the opportunity form", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.recommendedMatching", "ai", "Recommended opportunities, matched to a freelancer’s skills", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.profileSummary", "ai", "Professional summary drafts on the profile form", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.profileReview", "ai", "Recommended improvements on a freelancer’s profile review", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.projectApproach", "ai", "Approach drafts on an opportunity application", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.applicationEvaluation", "ai", "Evaluation notes on an opportunity application", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.requirementsSuggestion", "ai", "Technical requirements drafted on the opportunity form", Default: "true", HelpRequired: true, IsBoolean: true),
        new("ai.features.criteriaSuggestion", "ai", "Scoring rubric drafted on the opportunity form", Default: "true", HelpRequired: true, IsBoolean: true),

        // ai evals — the golden-set eval tool's own provider and key
        // (tests/WinnersPortal.AiEvals), kept apart from the AI setup so a
        // run never spends the portal's key or its daily ceiling, and not
        // governed by the AI switch. The portal never reads them; the tool
        // reads them from this database. What is saved here wins, as for
        // every setting: WP_EVAL_PROVIDER and WP_EVAL_API_KEY in the tool's
        // shell fill in only while it is blank.
        // The switch comes first: the tool refuses to run while it is off,
        // so a key saved here spends nothing until someone turns it on.
        new(Ai.EvalSettings.EnabledKey, Ai.EvalSettings.Group, "Enable AI evals", Default: "false", HelpRequired: true, IsBoolean: true),
        new(Ai.EvalSettings.ProviderKey, Ai.EvalSettings.Group, "Eval provider", HelpRequired: true,
            Choices: [.. AiProviders.Choices.Select(c => new SettingChoice(c.Value, c.Label))]),
        new(Ai.EvalSettings.ApiKeyKey, Ai.EvalSettings.Group, "Eval API key", IsSecret: true, HelpRequired: true,
            Trimmed: true),
        // The run’s own ceiling and timeout, read by the tool the same way.
        new(Ai.EvalSettings.MaxCallsKey, Ai.EvalSettings.Group, "Calls per eval run", Default: $"{Ai.EvalSettings.DefaultMaxCalls}", HelpRequired: true),
        new(Ai.EvalSettings.TimeoutKey, Ai.EvalSettings.Group, "Eval call timeout (seconds)", Default: $"{Ai.EvalSettings.DefaultTimeoutSeconds}", HelpRequired: true),

        // legal — versioned text; entrants re-accept when the version bumps
        new("legal.termsVersion", "legal", "Terms version", Default: "1", HelpRequired: true),
        new("legal.termsMarkdown", "legal", "Terms of service (Markdown)", HelpRequired: true, IsMultiline: true),
        new(Privacy.MarkdownKey, "legal", "Privacy policy (Markdown)", HelpRequired: true, IsMultiline: true),

        // notifications
        new("notifications.digestHourUtc", "notifications", "Daily digest hour (UTC)", Default: "9", HelpRequired: true),

        // limits & maintenance
        new("limits.maxEntriesPerOpportunity", "limits", "Max entries per opportunity", Default: "0", HelpRequired: true),
        new("limits.maxUploadMb", "limits", "Max upload size (MB)", Default: "25", HelpRequired: true),
        new("limits.captchaSiteKey", "limits", "Captcha site key", HelpRequired: true),
        new("limits.captchaSecret", "limits", "Captcha secret", IsSecret: true, HelpRequired: true),
        new("limits.maintenanceMode", "limits", "Maintenance mode", Default: "false", HelpRequired: true, IsBoolean: true),
        new(Activity.ActivityRetention.Key, "limits", "Activity log retention (days)", Default: "90", HelpRequired: true),
        new(Notifications.InboxRetention.Key, "limits", "Notification inbox retention (days)", Default: "90", HelpRequired: true),
        new(Infrastructure.Data.SlowQueryStats.SettingKey, "limits", "Slow-query threshold (ms)", Default: "500", HelpRequired: true),
        new(Infrastructure.Data.SlowQueryStats.BackgroundSettingKey, "limits", "Include background work in slow queries",
            Default: "true", HelpRequired: true, IsBoolean: true),
        new(Common.PublicReads.SettingKey, "limits", "Public page cache (seconds)",
            Default: $"{Common.PublicReads.DefaultSeconds}", HelpRequired: true),

        // redis — whether this process uses Redis, and where. One process
        // needs none, so off by default; read once at startup
        // (Settings/RedisSettings.cs), so a saved change waits for the
        // next restart, as the JWT group does.
        new(RedisSettings.EnabledKey, RedisSettings.Group, "Use Redis", Default: "false", HelpRequired: true, IsBoolean: true),
        new(RedisSettings.UrlKey, RedisSettings.Group, "Redis address", HelpRequired: true),

        // jwt — what a sign-in token says, what signs it, and how long the
        // bearer pair lasts. Read once at startup (Auth/JwtSettings.cs), so a
        // saved change waits for the next restart. The key has no default:
        // the first start stores one, and it is only ever replaced.
        new(Auth.JwtSettings.IssuerKey, Auth.JwtSettings.Group, "Issuer",
            Default: Auth.JwtSettings.DefaultIssuer, HelpRequired: true),
        new(Auth.JwtSettings.AudienceKey, Auth.JwtSettings.Group, "Audience",
            Default: Auth.JwtSettings.DefaultAudience, HelpRequired: true),
        new(Auth.JwtSettings.SigningKeyKey, Auth.JwtSettings.Group, "Signing key (leave blank to keep current key)",
            IsSecret: true, HelpRequired: true),
        new(Auth.JwtSettings.AccessMinutesKey, Auth.JwtSettings.Group, "Access token lifetime (minutes)",
            Default: $"{Auth.JwtSettings.DefaultAccessMinutes}", HelpRequired: true),
        new(Auth.JwtSettings.RefreshDaysKey, Auth.JwtSettings.Group, "Refresh token lifetime (days)",
            Default: $"{Auth.JwtSettings.DefaultRefreshDays}", HelpRequired: true),

        // integrations & feature flags
        new("features.publicMilestoneBoard", "integrations", "Public milestone board", Default: "true", HelpRequired: true, IsBoolean: true),
    ];

    private static readonly Dictionary<string, SettingDefinition> ByKey =
        All.ToDictionary(d => d.Key, StringComparer.Ordinal);

    /// <summary>
    /// A setting by key — including a field of a setup other than the main
    /// one (<c>github.s1a2b3c4d.appId</c>), which is its main field under its
    /// own key, without a default that only described the local stack.
    /// </summary>
    public static SettingDefinition? Find(string key)
    {
        if (ByKey.TryGetValue(key, out var def)) return def;
        if (Setups.ParseScoped(key) is not { } scoped || !ByKey.TryGetValue(scoped.FieldKey, out var field))
            return null;
        return field with { Key = key, Default = field.MainOnlyDefault ? null : field.Default };
    }

    /// <summary>The main key a key stands for: itself, or the field a setup's key is a copy of.</summary>
    public static string MainKey(string key) => Setups.ParseScoped(key)?.FieldKey ?? key;

    public static string EnvVarName(string key) =>
        "WP_" + key.Replace('.', '_').ToUpperInvariant();
}
